name: "CloudFlare Remove DNS Record"
description: "Removes CloudFlare DNS record"
author: "ScottRocha"

inputs:
  id:
    description: "DNS record ID"
  name:
    description: "DNS record name"
  token:
    description: "CloudFlare API token"
    required: true
  zone:
    description: "CloudFlare zone"
    required: true

runs:
  using: "node12"
  main: "main.js"

branding:
  icon: "cloud"
  color: "orange"
